### ISSUE TITLE
Easier way to do POI point/polygon tables?

### ISSUE THREAD

**Issue by pnorman** [pnorman/ClearTables#37]
It will be common to have pairs of tables like

``` yml
- name: education_point
  type: point
  comment: Education facilities mapped as points
  tagtransform: education.lua
  tagtransform-node-function: education_nodes
  tagtransform-way-function: drop_all
  tagtransform-relation-function: drop_all
  tagtransform-relation-member-function: drop_all
  tags:
  - <<: *name
  - <<: *names
  - &education
    name: education
    type: text
    comment: Type of education facility
- name: education_poly
  type: polygon
  comment: Education facilities mapped as polygons
  tagtransform: education.lua
  tagtransform-node-function: drop_all
  tagtransform-way-function: education_ways
  tagtransform-relation-function: education_rels
  tagtransform-relation-member-function: education_rel_members
  tags:
  - <<: *name
  - <<: *names
  - <<: *education
  - <<: *way_area
```

It'd be nice to be able to specify these only once and have it expanded by script, also creating a view which UNION ALLs them
